// <auto-generated />
using System;
using Kidev.Storage.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kidev.Storage.PostgreSQL.Migrations
{
    [DbContext(typeof(KidevDbContext))]
    [Migration("20260905171619_AddJobExecutionHistory")]
    partial class AddJobExecutionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kidev.Core.Data.JobDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("assembly_name");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_executed_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("method_name");

                    b.Property<string>("MethodParameterTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("method_parameter_types");

                    b.Property<DateTimeOffset>("NextExecutionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_execution_at_utc");

                    b.Property<string>("RegistrationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("registration_key");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("service_type_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationKey")
                        .IsUnique();

                    b.HasIndex(new[] { "NextExecutionAtUtc", "LeaseExpiresAtUtc", "Id" }, "ix_job_definitions_claimable")
                        .HasFilter("is_enabled = true");

                    b.HasIndex(new[] { "NextExecutionAtUtc", "Id" }, "ix_job_definitions_due")
                        .HasFilter("is_enabled = true");

                    b.ToTable("job_definitions", (string)null);
                });

            modelBuilder.Entity("Kidev.Core.Data.JobExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_type");

                    b.Property<int>("JobDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("job_definition_id");

                    b.Property<DateTimeOffset>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<DateTimeOffset>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("JobDefinitionId", "StartedAtUtc");

                    b.HasIndex("Status", "CompletedAtUtc");

                    b.ToTable("job_executions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
