// <auto-generated />
using System;
using Kidev.Storage.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kidev.Storage.PostgreSQL.Migrations
{
    [DbContext(typeof(KidevDbContext))]
    partial class KidevDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kidev.Core.Data.JobDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arguments");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("assembly_name");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_executed_at_utc");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("method_name");

                    b.Property<string>("MethodParameterTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("method_parameter_types");

                    b.Property<DateTimeOffset>("NextExecutionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_execution_at_utc");

                    b.Property<string>("RegistrationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("registration_key");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("service_type_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationKey")
                        .IsUnique();

                    b.HasIndex(new[] { "NextExecutionAtUtc", "Id" }, "ix_job_definitions_due")
                        .HasFilter("is_enabled = true");

                    b.ToTable("job_definitions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
