// Dependency-free Chromium smoke tests. Run: node Kidev.Dashboard.Tests/FactoryFrontendTests.mjs
// Set FACTORY_BROWSER to a Chromium executable if Brave is not installed.
import assert from "node:assert/strict";
import { readFile, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const read = path => readFile(join(root, path), "utf8");
const script = await read("Kidev.Dashboard/wwwroot/js/factory.js");
const styles = await read("Kidev.Dashboard/wwwroot/css/dashboard.css") + await read("Kidev.Dashboard/wwwroot/css/factory.css");
let shell = await read("Kidev.Dashboard/Areas/Kidev/Views/Visualization/Index.cshtml");
shell = shell.slice(shell.indexOf("<section class=\"factory\""), shell.indexOf("@section Scripts"));
shell = shell.replace(/data-snapshot-url="[^\n]+?data-details-url="[^\n]+?data-mode=/, 'data-snapshot-url="/host/operations/Visualization/Snapshot" data-details-url="/host/operations/Dashboard/Details" data-mode=');
shell = shell.replace(/@foreach[\s\S]+?\n                        }/, ["Succeeded", "Failed", "LeaseExpired"].map(state => `<section class="factory-outcome-group" data-outcome="${state}"><header><h3>${state}</h3><span data-outcome-count></span></header><div data-outcome-nodes class="factory-node-list"></div><p data-outcome-empty class="factory-empty"></p></section>`).join(""));
shell = shell.replace(/<partial[^>]+\/>/g, "");
const now = new Date().toISOString();
const ago = seconds => new Date(Date.parse(now) - seconds * 1000).toISOString();
const processId = "11111111111111111111111111111111";
const claimId = "22222222-2222-2222-2222-222222222222";
const process = { id: processId, name: "Billing / primary", machineName: "worker-host-01", processId: 4201, workerCount: 2, configuredWorkerCount: 2, startedAtUtc: ago(120), lastHeartbeatAtUtc: ago(3), state: "Online" };
const execution = { id: 10, jobDefinitionId: 7, registrationKey: "invoice.generate", methodName: "GenerateAsync", claimId, workerId: `${processId}:0`, processInstanceId: processId, startedAtUtc: ago(12), lastHeartbeatAtUtc: ago(3), leaseExpiresAtUtc: ago(-120), status: "Running" };
const initial = { observedAtUtc: now, windowStartAtUtc: ago(120), isTruncated: false, processes: [process], jobs: [{ id: 8, registrationKey: "ledger.reconcile", methodName: "ReconcileAsync", nextExecutionAtUtc: ago(-90), isEnabled: true }], executions: [execution], events: [{ eventId: `${claimId}:Started`, jobDefinitionId: 7, claimId, workerId: execution.workerId, state: "Started", occurredAtUtc: ago(12) }] };
const html = `<!doctype html><html lang="en" data-theme="dark"><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>${styles}</style></head><body><main style="padding:24px"><h1>Visualization</h1>${shell}</main></body></html>`;
const server = createServer((request, response) => { response.setHeader("Content-Type", "text/html"); response.end(html); });
await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
const profile = await mkdtemp(join(tmpdir(), "kidev-factory-browser-"));
const browser = spawn(globalThis.process.env.FACTORY_BROWSER || "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser", ["--headless=new", "--disable-gpu", "--no-first-run", "--no-default-browser-check", "--remote-debugging-port=0", `--user-data-dir=${profile}`, "about:blank"], { stdio: ["ignore", "ignore", "pipe"] });
let socket;
try {
    const endpoint = await new Promise((resolve, reject) => {
        let output = "";
        const timeout = setTimeout(() => reject(new Error("Browser startup timeout")), 15000);
        browser.on("error", reject);
        browser.stderr.on("data", chunk => {
            output += chunk;
            const match = output.match(/DevTools listening on (ws:\/\/[^\s]+)/);
            if (match) { clearTimeout(timeout); resolve(match[1]); }
        });
    });
    const port = new URL(endpoint).port;
    const targets = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
    socket = new WebSocket(targets[0].webSocketDebuggerUrl);
    await new Promise(resolve => socket.addEventListener("open", resolve, { once: true }));
    let sequence = 0;
    const pending = new Map();
    const errors = [];
    socket.addEventListener("message", event => {
        const message = JSON.parse(event.data);
        if (message.method === "Runtime.exceptionThrown") errors.push(message.params.exceptionDetails);
        if (!message.id) return;
        const operation = pending.get(message.id);
        pending.delete(message.id);
        if (message.error) operation.reject(message.error);
        else operation.resolve(message.result);
    });
    const send = (method, params = {}) => new Promise((resolve, reject) => {
        const id = ++sequence;
        pending.set(id, { resolve, reject });
        socket.send(JSON.stringify({ id, method, params }));
    });
    const evaluate = async expression => {
        const result = await send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true });
        if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
        return result.result.value;
    };
    const tick = () => new Promise(resolve => setTimeout(resolve, 80));
    const click = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
    const count = selector => evaluate(`document.querySelectorAll(${JSON.stringify(selector)}).length`);
    const mode = () => evaluate('document.querySelector("[data-factory]").dataset.mode');
    const refresh = async value => {
        await evaluate(`window.nextSnapshot = ${JSON.stringify(value)};`);
        await click("[data-factory-refresh]");
        await tick();
    };
    await send("Page.enable");
    await send("Runtime.enable");
    await send("Page.navigate", { url: `http://127.0.0.1:${server.address().port}/host/operations/Visualization` });
    await tick();
    await evaluate(`window.nextSnapshot = ${JSON.stringify(initial)}; window.requests = []; window.fail = false; window.hang = false; window.fetch = async (url, options) => { window.requests.push(url); if (window.hang) return new Promise((resolve, reject) => options.signal.addEventListener('abort', () => reject(new DOMException('Aborted', 'AbortError')))); if (window.fail) throw new Error('sensitive failure'); return {ok:true, redirected:false, json:async () => structuredClone(window.nextSnapshot)}; };`);
    await evaluate(script);
    await tick();
    assert.equal(await mode(), "live");
    assert.equal(await count(".factory-process"), 1);
    assert.equal(await count(".factory-slot"), 2);
    assert.equal(await count(".factory-connection-active"), 1);
    assert.equal(await count(".factory-enter, .factory-heartbeat, .factory-connection-outcome"), 0, "First snapshot must be baseline");
    assert.equal(await evaluate('window.requests[0]'), "/host/operations/Visualization/Snapshot");
    await evaluate('window.originalNode = document.querySelector("[data-key^=claim]"); window.originalNode.focus();');
    await refresh(initial);
    assert.equal(await evaluate('document.activeElement === window.originalNode'), true, "Stable identity preserves focus");
    assert.equal(await count(".factory-heartbeat"), 0);
    const heartbeat = structuredClone(initial);
    heartbeat.executions[0].lastHeartbeatAtUtc = now;
    await refresh(heartbeat);
    assert.equal(await count(".factory-heartbeat"), 1, "New persisted heartbeat flashes once");
    await click("[data-key^=claim]");
    assert.equal(await evaluate('document.activeElement.hasAttribute("data-factory-close")'), true);
    assert.match(await evaluate('document.querySelector(".factory-inspector a").href'), /\/host\/operations\/Dashboard\/Details\?id=7$/);
    await evaluate('document.querySelector(".factory-inspector a").focus()');
    await refresh(heartbeat);
    assert.equal(await evaluate('document.activeElement.matches(".factory-inspector a")'), true, "Inspector refresh preserves link focus");
    await evaluate('document.activeElement.dispatchEvent(new KeyboardEvent("keydown", {key:"Escape", bubbles:true}))');
    assert.equal(await evaluate('document.activeElement === window.originalNode'), true);
    const completed = structuredClone(heartbeat);
    completed.executions[0].status = "Failed";
    completed.executions[0].completedAtUtc = now;
    completed.executions[0].errorMessage = '<img src=x onerror="window.pwned=true">';
    completed.events.unshift({ eventId: `${claimId}:Finished`, claimId, state: "Failed", occurredAtUtc: now });
    await refresh(completed);
    assert.equal(await evaluate('document.activeElement === window.originalNode'), true, "Moving to an outcome preserves keyboard focus");
    assert.equal(await count('.factory-connection-active'), 0);
    assert.equal(await count('.factory-connection-outcome'), 1);
    await click('[data-key^=claim]');
    assert.equal(await count('.factory-inspector img'), 0);
    assert.match(await evaluate('document.querySelector("[data-factory-inspector-content]").textContent'), /<img src=x/);
    assert.equal(await count('.factory-history li'), 2);
    assert.match(await evaluate('document.querySelector(".factory-history li").textContent'), /Started/);
    await refresh(completed);
    assert.equal(await count('.factory-connection-outcome'), 0, "Overlapping event must not replay");
    assert.equal(await count('.factory-history li'), 2);
    await click('[data-factory-pause]');
    const frozen = await evaluate('document.querySelector("[data-factory-stage]").textContent');
    await evaluate(`window.nextSnapshot = ${JSON.stringify(initial)};`);
    await new Promise(resolve => setTimeout(resolve, 2100));
    assert.equal(await mode(), "paused");
    assert.equal(await evaluate('document.querySelector("[data-factory-stage]").textContent'), frozen);
    await click('[data-factory-pause]');
    await tick();
    assert.equal(await mode(), "live");
    assert.equal(await count('.factory-connection-active'), 1);
    assert.equal(await count('.factory-enter, .factory-connection-outcome'), 0, "Resume reconciles without replay");
    await evaluate('window.fail = true');
    await click('[data-factory-refresh]');
    await tick();
    assert.equal(await mode(), "error");
    assert.equal(await evaluate('getComputedStyle(document.querySelector(".factory-connection-active")).animationName'), "none");
    assert.doesNotMatch(await evaluate('document.body.textContent'), /sensitive failure/);
    await evaluate('window.fail = false');
    const stale = structuredClone(initial);
    stale.processes[0].state = "Stale";
    await refresh(stale);
    assert.equal(await count('.factory-worker[data-state="Idle"]'), 0);
    assert.equal(await count('.factory-worker[data-state="Unknown"]'), 2);
    assert.equal(await count('.factory-connection-active'), 0);
    const truncated = structuredClone(initial);
    truncated.isTruncated = true;
    await refresh(truncated);
    assert.equal(await count('.factory-worker[data-state="Idle"]'), 0, "Truncation cannot establish idle workers");
    assert.equal(await count('.factory-worker[data-state="Running"]'), 1);
    const recurring = structuredClone(completed);
    recurring.executions.push({ ...execution, claimId: "33333333-3333-3333-3333-333333333333", id: 11 });
    await refresh(recurring);
    assert.equal(await count('[data-key^=claim]'), 2, "Recurring attempts retain separate claim identities");
    assert.equal(await count('.factory-connection-active'), 1);
    const unknown = structuredClone(initial);
    unknown.processes = [];
    await refresh(unknown);
    assert.equal(await count('.factory-slot'), 0);
    assert.equal(await evaluate('document.querySelector("[data-factory-unregistered]").hidden'), false);
    const bounded = structuredClone(initial);
    bounded.processes = Array.from({length:21}, (_, index) => ({...process, id:`process-${index}`, workerCount:100}));
    await refresh(bounded);
    assert.equal(await count('.factory-process'), 20);
    assert.equal(await count('.factory-slot'), 128);
    assert.equal(await evaluate('document.querySelector("[data-factory-limit]").hidden'), false);
    await refresh(initial);
    await click('[data-factory-close]');
    if (globalThis.process.env.FACTORY_SCREENSHOT) {
        await send("Emulation.setDeviceMetricsOverride", { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
        await new Promise(resolve => setTimeout(resolve, 750));
        const image = await send("Page.captureScreenshot", { format: "png" });
        await writeFile(globalThis.process.env.FACTORY_SCREENSHOT, Buffer.from(image.data, "base64"));
    }
    for (const width of [1440, 1024, 390, 320]) {
        await send("Emulation.setDeviceMetricsOverride", { width, height: 900, deviceScaleFactor: 1, mobile: false });
        for (const theme of ["dark", "light"]) {
            await evaluate(`document.documentElement.dataset.theme = '${theme}'`);
            assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true, `Page overflow: ${width}px ${theme}`);
        }
    }
    await click('[data-factory-table-toggle]');
    assert.equal(await evaluate('document.querySelector("#factory-viewport").hidden'), true);
    assert.equal(await count('[data-factory-rows] tr'), 5);
    await click('[data-factory-table-toggle]');
    await send("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] });
    assert.equal(await evaluate('getComputedStyle(document.querySelector(".factory-connection-active")).animationName'), "none");
    await evaluate('Object.defineProperty(document, "hidden", {configurable:true, value:true}); document.dispatchEvent(new Event("visibilitychange"));');
    assert.equal(await mode(), "hidden");
    const requestCount = await evaluate('window.requests.length');
    await new Promise(resolve => setTimeout(resolve, 2100));
    assert.equal(await evaluate('window.requests.length'), requestCount, "Hidden tab stops polling");
    await evaluate('Object.defineProperty(document, "hidden", {configurable:true, value:false}); document.dispatchEvent(new Event("visibilitychange"));');
    await tick();
    assert.equal(await mode(), "live");
    await evaluate('window.hang = true');
    await click('[data-factory-refresh]');
    await tick();
    const inflightCount = await evaluate('window.requests.length');
    await click('[data-factory-refresh]');
    assert.equal(await evaluate('window.requests.length'), inflightCount, "No overlapping requests");
    await click('[data-factory-pause]');
    await evaluate('window.hang = false');
    await click('[data-factory-pause]');
    await tick();
    assert.equal(await mode(), "live", "Aborted in-flight resume recovers");
    await evaluate('window.hang = true');
    await click('[data-factory-refresh]');
    await new Promise(resolve => setTimeout(resolve, 8200));
    assert.equal(await mode(), "error", "Request timeout stops active motion");
    assert.deepEqual(errors, []);
    console.log("PASS: Visualization browser lifecycle, stable nodes/focus, heartbeat facts, outcome dedup/order, safe inspector, pause/resume, stale/unknown ownership, DOM bounds, table, light/dark at four widths, reduced motion, hidden-tab suspension, abort/no overlap.");
} finally {
    socket?.close();
    browser.kill();
    server.close();
    await new Promise(resolve => browser.once("exit", resolve));
    await rm(profile, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
}
